### ISSUE TITLE
ITM/`iprint` send data in 32-bit chunks

### ISSUE THREAD

**Issue by japaric** [japaric/f3#9]
Be careful with alignment.

**Comment by japaric** [comment]
Note to self: benchmark this with the `time` module

**Comment by jcsoo** [comment]
Have you noticed any problems losing output when sending data quickly? I'm running the same code on the F4 and sometimes lose characters.

I have a feeling that it may be dropping it on the ST-Link side, unfortunately.

**Comment by japaric** [comment]
> Have you noticed any problems losing output when sending data quickly?

Not yet but I haven't tried high throughput either.

I wouldn't expect it to lose data though. The `iprintln` has a busy wait loop in it to prevent queuing more data if the bus is already busy. I'd expect that to "throttle" the data rate.

> I have a feeling that it may be dropping it on the ST-Link side, unfortunately.

FWIW, the ST-LINK is an STM32F1 device and I doubt it's clocked at a high frequency.

**Comment by japaric** [comment]
Done in cortex-m some time ago.
